<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Logitech C930 camera -->
    <xacro:macro name="logitech_c930" params="parent_link sensor_name visualize x y z roll pitch yaw">

        <!-- Variables -->
        <xacro:property name="frame_length" value="0.025"/>
        <xacro:property name="frame_width"  value="0.090"/>
        <xacro:property name="frame_height" value="0.028"/>

        <!-- Links -->
        <link name="${sensor_name}">

            <!-- Mesh -->
            <visual>
                <origin xyz="0 0 ${frame_height/2}" rpy="0 0 0" />
                <geometry>
                    <mesh filename="file://$(find carsa_gazebo)/meshes/logitech_c930.dae" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>

        </link>

        <link name="${sensor_name}_optical">

            <!-- Mesh -->
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="file://$(find carsa_gazebo)/meshes/logitech_camera_lens.dae" scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>
        </link>

        <!-- Joints -->
        <joint name="${sensor_name}_joint" type="fixed">

            <!-- Origin -->
            <origin xyz="${x} ${y} ${z}" rpy="${radians(roll)} ${radians(pitch)} ${radians(yaw)}" />

            <!-- Frame ID -->
            <parent link="${parent_link}" />
            <child link="${sensor_name}" />
            
        </joint>

        <joint name="${sensor_name}_optical_joint" type="fixed">

            <!-- Origin -->
            <!-- <origin xyz="0 0 ${frame_height/2}" rpy="${-pi/2} 0 ${-pi/2}" /> -->
            <origin xyz="0 0 ${frame_height/2}" rpy="0 0 0" />

            <!-- Frame ID -->
            <parent link="${sensor_name}" />
            <child link="${sensor_name}_optical" />

        </joint>

        <!-- Gazebo plugin -->
        <gazebo reference="${sensor_name}_optical">

            <!-- Sensor properties -->
            <sensor name="${sensor_name}" type="camera">

                <!-- Topic -->
                <update_rate>30</update_rate>
                <always_on>true</always_on>
                <visualize>${visualize}</visualize>

                <!-- Optical -->
                <camera>

                    <!-- FOV-->
                    <horizontal_fov>1.167485</horizontal_fov>

                    <!-- Data formats -->
                    <image>
                        <width>640</width>
                        <height>480</height>
                        <format>R8G8B8</format>
                    </image>

                    <!-- Detection area -->
                    <clip>
                        <near>0.05</near>
                        <far>100.0</far>
                    </clip>

                    <!-- Distortion -->
                    <!--
                    <distortion>
                        <k1>0.162875</k1><k2>-0.287212</k2><k3>0.0</k3>
                        <p1>0.000692</p1><p2>-0.000678</p2>
                        <center><x>291.5055</x><y>222.6638</y></center>
                    </distortion>
                    -->

                </camera>

                <!-- Gazebo ROS camera plugin -->
                <plugin name="${sensor_name}_plugin" filename="libgazebo_ros_camera.so">
                    <camera_name>${sensor_name}</camera_name>
                    <image_topic_name>${sensor_name}/image_raw</image_topic_name> 
                    <camera_info_topic_name>${sensor_name}/camera_info</camera_info_topic_name>
                    <frame_name>${sensor_name}_optical</frame_name>
                </plugin>

            </sensor>
        </gazebo>

    </xacro:macro>

</robot>